#!/usr/bin/env zsh

# Shorten frequently used commands
alias v="nvim"
alias p="python3"
alias j="julia"
alias ssh="kitten ssh"

# Always use a colored output for 'ls' command
alias ls="command ls -1FG"

# List all files in a colorized long format
alias ll="command ls -lhFG"

# List all files, including hidden files, in a colorized long format
alias la="command ls -lhAFG"

# List only directories in a colorized format
alias lsd="command ls -1dG */"

# List only directories in a colorized long format
alias lld="command ls -lhdG */"

# List only directories, including hidden directories, in a colorized long format
alias lad="command ls -lhdG .*/ */"

# Move to the directory containing dotfiles
alias dotfiles="cd ~/Coding/Personal/Dotfiles"

# Move to the directory containing the source code for my master thesis
alias thesis="cd ~/Coding/School/MasterThesis"

# Move to the directory containing the source code for Neural Bayesian Filtering
alias nbf="cd ~/Research/Donuts"

# Move to the directory containing the source code for Belief Embedding Tree Search
alias bets="cd ~/Research/Bets"

# Update all CLI and GUI applications
alias update="brew update; brew upgrade; brew cleanup -s"

# Show/Hide all desktop icons
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Restart WiFi
alias wifi="sudo ifconfig en0 down && sudo ifconfig en0 up"

# Flush DNS cache
alias flushdns="sudo killall -HUP mDNSResponder; sleep 1"
