#!/usr/bin/env zsh

# Print each 'PATH' entry on a separate line
function path {
    echo "$PATH" | tr ':' '\n'
}

# Create '.venv' in a given directory if not present and source it
function venv {
    local venv_path="${1:-.}/.venv"

    if [[ ! -d "$venv_path" ]]; then
        python3 -m venv "$venv_path"
    fi

    source "$venv_path"/bin/activate
}

# Generate a random password of a given length
function rand_passwd {
    local passwd_len="${1:-15}"

    echo -n $(openssl rand -base64 $passwd_len)

    # Add a new line when outputting to a terminal
    [ -t 1 ] && echo ''
}
