#!/usr/bin/env zsh

# Print each 'PATH' entry on a separate line
function path {
    echo "$PATH" | tr ':' '\n'
}

# Create '.venv' in a given directory if not present and source it
function venv {
    local venv_path="${1:-.}/.venv"

    if [[ ! -d "$venv_path" ]]; then
        python3 -m venv "$venv_path"
    fi

    source "$venv_path"/bin/activate
}
