#!/usr/bin/env zsh

# Automatically hide and show the menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true

# Automatically hide and show the dock
defaults write com.apple.dock autohide -bool true

# Set a size of icons on the dock
defaults write com.apple.dock tilesize -int 60
defaults write com.apple.dock largesize -int 70

# Set fast key repeats
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Disable press-and-hold and allow key repeats
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
