#!/usr/bin/env zsh

# Set fast key repeats
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Set a size of icons on the Dock
defaults write com.apple.dock tilesize -int 60
defaults write com.apple.dock largesize -int 70
